# Generated by Django 3.2.9 on 2021-12-18 12:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='full_description',
            field=tinymce.models.HTMLField(default='write here full description'),
            preserve_default=False,
        ),
    ]
