# Generated by Django 3.2.9 on 2021-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='full_description',
            field=models.TextField(),
        ),
    ]
