# Generated by Django 3.2.9 on 2021-12-20 09:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[710, 820], upload_to=''),
        ),
    ]
