# Generated by Django 3.2.9 on 2021-12-20 09:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
