# Generated by Django 3.2.9 on 2021-12-20 09:54

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211220_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
