# Generated by Django 3.2.9 on 2021-12-20 11:43

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211220_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Earphone', 'Earphone'), ('Android', 'Android'), ('Tshirt', 'T Shirt'), ('Shoe', 'Shoe'), ('Gadget', 'Gadget')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
    ]
