# Generated by Django 3.2.9 on 2021-12-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211220_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
